spring:
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    host: smtp.gmail.com
    username: chogaytam@gmail.com
    password: bxpdcssrphmmxgjr
    port: '587'
  profiles:
    active: dev
PAYOS_CREATE_PAYMENT_LINK_URL: https://api-merchant.payos.vn/v2/payment-requests
PAYOS_API_KEY: 0cdcad04-9e1e-4b85-82f2-e10c466a2d16
PAYOS_CHECKSUM_KEY: 807e8dca774da598d04ffb0816cd93020c2c37c34846f6f3536faa0f5d47df76
PAYOS_CLIENT_ID: 9493a6a9-258f-4022-b69f-7b5ebb2274e7
server:
  servlet:
    application-display-name: birdFarmShop
